"""
Shared fixtures for PDE Solver benchmark tests.

Tests import the pdesolver module directly. The workspace path is discovered
from the ENGINE_CMD environment variable (set by the harness) or
defaults to the current working directory.
"""
import sys
import os
import pytest
import numpy as np

# ---------------------------------------------------------------------------
# Workspace discovery
# ---------------------------------------------------------------------------
_engine_cmd = os.environ.get("ENGINE_CMD", "")
if _engine_cmd and "cd " in _engine_cmd:
    _workspace = _engine_cmd.split("&&")[0].replace("cd ", "").strip()
    sys.path.insert(0, _workspace)
else:
    sys.path.insert(0, os.getcwd())

# Path to reference data generated by reference solutions
REF_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "reference_solutions", "data")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_ref(name):
    """Load a reference .npz file by name (e.g. 'ref_1_1')."""
    path = os.path.join(REF_DATA_DIR, f"{name}.npz")
    if not os.path.exists(path):
        pytest.skip(f"Reference data {name}.npz not found")
    return np.load(path)


def l2_error(computed, reference):
    """Compute RMS (L2) error between two arrays."""
    return np.sqrt(np.mean((computed - reference) ** 2))


def max_error(computed, reference):
    """Compute max absolute error between two arrays."""
    return np.max(np.abs(computed - reference))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def sim_factory():
    """Factory for creating Simulation objects with custom parameters."""
    import pdesolver

    def _make(**kwargs):
        return pdesolver.Simulation(**kwargs)

    return _make


@pytest.fixture
def ref_data():
    """Load reference data by name."""
    return load_ref
